@startuml
hide footbox
agent "Content\nCreator" as Creator
agent "Content\nConsumer" as Consumer
cloud "Share Content" as cloud
Creator -> cloud : ContentCreator
cloud -> Consumer : ContentConsumer
@enduml
