# sushi-config.yaml is documented https://fshschool.org/docs/sushi/configuration/
# ───────────────────────────────────────────────────
# the id should be lowercase made up of "ihe." + {domain acronym} + "." + {profile acronym/short-name}
# e.g. ihe.iti.mhds, or ihe.iti.basicaudit
id: ihe.pcc.maps
canonical: https://profiles.ihe.net/PCC/mAPS
version: 1.0.0-comment
name: IHE_PCC_MAPS
title: "Mobile Antepartum Summary"
description: Antepartum Summary is a content profile that defines the structure for the aggregation of significant events, diagnoses, and plans of care derived from the visits over the course of an antepartum episode.
#releaseLabel: ci-build
releaseLabel: ballot
#releaseLabel: trial-use
#releaseLabel: release
date: 2024-06-04
status: active
publisher:
  ## Find your domain contact on the https://www.ihe.net/ihe_domains page
  - name: IHE Patient Care Coordination Committee
  - url: https://www.ihe.net/ihe_domains/patient_care_coordination/
  - email: pcc@ihe.net
contact:
  - name: IHE Patient Care Coordination Committee
    telecom:
      - system: email
        value: pcc@ihe.net
license:  CC-BY-4.0
fhirVersion: 4.0.1
jurisdiction: 'http://unstats.un.org/unsd/methods/m49/m49.htm#001'
#copyright: IHE http://www.ihe.net/Governance/#Intellectual_Property
copyrightYear: 2021+

dependencies:
  hl7.fhir.uv.ips:
    id: hl7ips
    uri: http://hl7.org/fhir/uv/ips/ImplementationGuide/hl7.fhir.uv.ips
    version: 1.1.x
  ihe.pcc.odh: 
    id: ihepccodh
    version: 1.0.0-comment
  ihe.iti.pdqm: 
    id: ihepdqm
    uri: https://profiles.ihe.net/ITI/PDQm/ImplementationGuide/ihe.iti.pdqm
    version: 3.0.x


parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - fsh-generated/resources
    - input/examples
#  path-pages:
#    - input/pagecontent
#    - fsh-generated/includes
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'false'
  logging: progress
  shownav: 'true'
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'

resources:
# list every example here with a name, description and that exampleBoolean is true; These are used to populate the artifacts page, and are needed to eliminate build warnings 
# You may delay filling out this section until you approach publication as it is merely a nice to have and eliminates build warnings -- If you do this then you will need above the autoload-resources true
  List/genetic:
    name:  Example Amanda Alvarez 
    description: Example Amanda Alvarez documents what an example compositoin for an Antepartum Summary should look like as well as what observations should be included within the composition. 
    exampleBoolean: true
#    name: Genetic List
#    description: TODO
#    exampleBoolean: true

pages:
# itemize here each narrative page. Include assigned section numbers when appropriate. The order they appear here is the order they will appear in the TOC and on the next/prev navigation.
  index.md:
    title: Mobile Antepartum Summary (mAPS) Home
    generation: markdown
  volume-1.md:
    title: 1:XX Mobile Antepartum Summary (mAPS) Volume 1
    generation: markdown
  volume-3.md:
    title: 3:YY Mobile Antepartum Summary (mAPS) Content
    generation: markdown
  testplan.md:
    title: "Test Plan"
    generation: markdown
  other.md:
    title: Changes to Other IHE Specifications
    generation: markdown
  download.md:
    title: "Download and Analysis"
    generation: markdown
  issues.md:
    title: Significant Changes and Issues
    generation: markdown

menu:
  Home: index.html
  Volume 1:
    Introduction: volume-1.html
    Actors and Transactions: volume-1.html#actors-and-transactions
    Actor Options: volume-1.html#actor-options
    Required Actor Groupings: volume-1.html#required-groupings
    Overview: volume-1.html#overview
    Security Considerations: volume-1.html#security-considerations
    Cross-Profile Considerations: volume-1.html#other-grouping
  Volume 3:
    "Mobile Antepartum Summary (mAPS) Content": volume-3.html
  Artifacts: artifacts.html
  Other:
    Changes to Other IHE Specifications: other.html
    Download and Analysis: download.html
    Test Plan: testplan.html

